#!/usr/bin/env python3
"""D.2 step 1: rerun the 2x2 factorial on ``rho_offered``.

``rho_offered`` is generated by the traffic model and does not pass through
the TX-counter measurement path.  The key cell therefore separates a
generator/endpoint effect from shared measurement noise without a new
Mininet run.
"""
from __future__ import annotations

import glob
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd


CAMPAIGN = "results/RAW/phase-23/aoi_v7_campaign"
OUT = Path("results/SMOKE/phase-D/factorial_offered.json")
DT = 0.01

HOST = {
    "uA": ("hsrc", "hA"),
    "uB": ("hsrc", "hB"),
    "ac": ("hA", "hC"),
    "ad": ("hA", "hD"),
    "bc": ("hB", "hC"),
    "bd": ("hB", "hD"),
    "vC": ("hC", "hdst"),
    "vD": ("hD", "hdst"),
}
SIGMA = {key: (0.10 if key in ("ac", "ad", "bc", "bd") else 0.03) for key in HOST}
LINKS = list(HOST)


def fisher_z(rho: float) -> float:
    return float(np.arctanh(np.clip(rho, -0.999, 0.999)))


def fisher_inverse(value: float) -> float:
    return float(np.tanh(value))


def acf(values: np.ndarray, nlag: int) -> np.ndarray:
    centered = np.asarray(values, dtype=float) - np.mean(values)
    n = len(centered)
    variance = centered @ centered / n
    if variance <= 0:
        return np.concatenate(([1.0], np.zeros(nlag)))
    return np.array(
        [centered[: n - lag] @ centered[lag:] / n / variance for lag in range(nlag + 1)]
    )


def tau_int(values: np.ndarray, dt: float = DT) -> float:
    """Integral time scale, cut at the first non-positive ACF lag."""
    curve = acf(values, min(len(values) // 10, 20_000))
    cut = len(curve) - 1
    for lag in range(1, len(curve)):
        if curve[lag] <= 0:
            cut = lag - 1
            break
    return dt * (0.5 + curve[1 : cut + 1].sum())


def main() -> None:
    rows: list[dict[str, object]] = []
    per_run: dict[str, list[float]] = {}
    run_diagnostics: list[dict[str, object]] = []
    files = sorted(glob.glob(f"{CAMPAIGN}/rho_offered_clean_*.csv"))
    if not files:
        raise FileNotFoundError("no rho_offered_clean_*.csv files found")

    for filename in files:
        frame = pd.read_csv(filename)
        wide = frame.pivot_table(index="sample_index", columns="link", values="rho_offered")
        missing = [link for link in LINKS if link not in wide]
        if missing:
            raise ValueError(f"{filename}: missing links {missing}")
        taus = {link: tau_int(wide[link].to_numpy()) for link in LINKS}
        burn = int(5 * max(taus.values()) / DT)
        window = wide.iloc[burn:]
        run_diagnostics.append(
            {
                "file": filename,
                "tau_max_s": round(max(taus.values()), 6),
                "burn_samples": burn,
                "samples_after_burn": len(window),
            }
        )
        if len(window) < 50:
            continue
        for i, first in enumerate(LINKS):
            for second in LINKS[i + 1 :]:
                rho = float(np.corrcoef(window[first], window[second])[0, 1])
                per_run.setdefault(f"{first}-{second}", []).append(rho)

    for pair, values in per_run.items():
        first, second = pair.split("-")
        rows.append(
            {
                "pair": pair,
                "r_fisher_pooled": round(
                    fisher_inverse(float(np.mean([fisher_z(value) for value in values]))), 4
                ),
                "n_runs": len(values),
                "n_runs_negative": int(sum(value < 0 for value in values)),
                "sd_across_runs": round(float(np.std(values, ddof=1)), 4),
                "n_low_sigma": int(SIGMA[first] == 0.03) + int(SIGMA[second] == 0.03),
                "shared_host": bool(set(HOST[first]) & set(HOST[second])),
            }
        )

    grouped: dict[str, list[dict[str, object]]] = {}
    for pair in rows:
        key = f"nlow{pair['n_low_sigma']}_shared{int(pair['shared_host'])}"
        grouped.setdefault(key, []).append(pair)
    cells = {
        key: {
            "n": len(values),
            "fisher_pooled_r": round(
                fisher_inverse(
                    float(np.mean([fisher_z(float(pair["r_fisher_pooled"])) for pair in values]))
                ),
                4,
            ),
            "pairs": [pair["pair"] for pair in values],
        }
        for key, values in sorted(grouped.items(), reverse=True)
    }

    key_value = float(cells["nlow2_shared1"]["fisher_pooled_r"])
    if abs(key_value) < 0.15:
        h6 = "SUPPORTED (offered clean: correlation arises in measurement layer)"
    elif key_value > 0.40:
        h6 = "REFUTED (offered remains high: correlation exists in generation layer)"
    else:
        h6 = "UNRESOLVED (intermediate offered result: both layers may contribute)"
    verdict = {
        "measured_reference": 0.6181,
        "offered_key_cell": key_value,
        "H6_shared_measurement_noise": h6,
    }
    artifact = {
        "schema": "dt4n.phase_d.factorial_offered.v1",
        "status": "POST_HOC_REANALYSIS_NOT_CONFIRMATORY",
        "field": "rho_offered",
        "burn_in_rule": "5 * tau_max per run",
        "n_files": len(files),
        "cells": cells,
        "pairs": rows,
        "run_diagnostics": run_diagnostics,
        "verdict": verdict,
        "provenance": {
            "git_hash": subprocess.run(
                ["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True
            ).stdout.strip(),
            "timestamp_utc": datetime.now(timezone.utc).isoformat(),
            "script": "tools/phase_d_factorial_offered.py",
        },
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(artifact, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"cells": cells, "verdict": verdict}, indent=2))


if __name__ == "__main__":
    main()
